update membership to user
yamilacasarini/restopassServer pull request #2
Opened 2020-05-25 20:39 UTC by csosa

2020-05-26 21:16 UTC, camubg approved these changes

2020-05-26 21:16 UTC, CamiGil commented on src/main/java/restopass/controller/MembershipController.java
> +        String userId = request.getAttribute(USER_ID_ATTR).toString();
hay chance de que getAttribute te devuelva null? Entiendo que no deberia porque el usuario esta loggeado en esa intancia pero bue

2020-05-26 21:16 UTC, CamiGil commented on src/main/java/restopass/service/MembershipService.java
> +            throw new InvalidUsernameOrPasswordException();
aca no seria lo de password creo

2020-05-26 21:16 UTC, CamiGil commented on src/main/java/restopass/service/UserService.java
> +        query.addCriteria(Criteria.where(EMAIL_FIELD).is(userId));
userId == email???

2020-05-26 21:21 UTC, yamilacasarini commented on src/main/java/restopass/service/UserService.java
> +        query.addCriteria(Criteria.where(EMAIL_FIELD).is(userId));
si

2020-05-26 21:22 UTC, yamilacasarini commented on src/main/java/restopass/service/MembershipService.java
> +            throw new InvalidUsernameOrPasswordException();
si puede ser, yo cree ese error generico para el login, pero aca estaria bueno especificar con un error nuevo que el usuario no existe

2020-05-26 21:23 UTC, yamilacasarini commented on src/main/java/restopass/controller/MembershipController.java
> +        String userId = request.getAttribute(USER_ID_ATTR).toString();
no, si devuelve null va a pinchar pero esta bien porque quiere decir que algo del request esta mal

2020-05-26 21:28 UTC, yamilacasarini requested changes

2020-05-26 21:28 UTC, yamilacasarini commented on src/main/java/restopass/service/MembershipService.java
> +        this.userService.updateMembership(userId, request.getMembershipId().name());
aca no es necesario el .name() porque implemente un converter del jackson que hace el save en mongo para que guarde el .ordinal() del enum, que despues nos facilita que sea un Integer para hacer comparaciones del tipo que plan es mayor o menor

2020-05-26 21:35 UTC, juanicabanas commented on src/main/java/restopass/service/MembershipService.java
> +            throw new InvalidUsernameOrPasswordException();
habría que cambiarlo sí

2020-05-26 21:36 UTC, juanicabanas approved these changes

2020-05-26 23:55 UTC, csosa commented on src/main/java/restopass/service/MembershipService.java
> +            throw new InvalidUsernameOrPasswordException();
Cambiado!

2020-05-26 23:56 UTC, csosa commented on src/main/java/restopass/service/MembershipService.java
> +        this.userService.updateMembership(userId, request.getMembershipId().name());
Buenisimo, ahi saque el .name()

2020-05-27 16:50 UTC, yamilacasarini approved these changes

2020-05-27 16:57 UTC, merged